http://localhost:3000/v1/pool/telemetry
Content-Type: application/json

{
  "user": "{{$dotenv OMNILOGIC_USER}}",
  "password": "{{$dotenv OMNILOGIC_PASSWORD}}"
}

###
http://localhost:3000/v2/pool/telemetry
Content-Type: application/json
x-omnilogic-user: {{$dotenv OMNILOGIC_USER}}e
x-omnilogic-password: {{$dotenv OMNILOGIC_PASSWORD}}

###
http://pool-api.apps.ansont.net/v1/pool/telemetry
Content-Type: application/json

{
  "user": "{{$dotenv OMNILOGIC_USER}}",
  "password": "{{$dotenv OMNILOGIC_PASSWORD}}"
}

###
http://localhost:8081/metrics